services:
  - type: web
    name: php-bot
    runtime: docker
    plan: free
    repo: https://github.com/punirah/biasa # Ganti dengan repo GitHub kamu
    branch: main
    dockerfilePath: Dockerfile
    healthCheckPath: /
    autoDeploy: false  # Supaya tidak restart otomatis
