services:
  - name: php-app
    image: php:8.2-apache
    ports:
      - 8080:80 # Mapping port 8080 di Render ke port 80 di container
    volumes:
      - ./biasa:/var/www/html # Mount direktori local ke dalam container
    environment:
      - CLEAR_CACHE: false
